<%@ page language="java" contentType="text/html; charset=ISO-8859-1" pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">

<html lang="en">

<head>

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="">
<meta name="author" content="">

<title>SB Admin 2 - Bootstrap Admin Theme</title>

<!-- Bootstrap Core CSS -->
<link href="scriptLibrary/bootstrap/css/bootstrap.min.css" rel="stylesheet">
<%-- <link href="<c:url value="/scriptLibrary/bootstrap/css/bootstrap.min.css" />" rel="stylesheet"> --%>


<!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

	<jsp:include page="pageHeader.jsp"></jsp:include>
	<div id="wrapper">

		<!-- Navigation -->


		<div id="page-wrapper">
			<form role="form">
				<div class="row">
					<div class="col-lg-12">
						<h1 class="page-header">Create New Document</h1>
					</div>
					<!-- /.col-lg-12 -->
				</div>
				<!-- /.row -->

				<div class="row">
					<div class="col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">Basic Information</div>
							<div class="panel-body">
								<div class="row">

									<fieldset>
										<div class="col-lg-6">
											<div class="form-group">
												<label>ID</label> <input class="form-control" disabled>
												<p class="help-block">User's identify number will be generated by system automatically.</p>
											</div>
										</div>
										<!-- /.col-lg-6 (nested) -->


										<div class="col-lg-6">
											<div class="form-group">
												<label>User Name</label> <input class="form-control" name="username">
												<p class="help-block">User's name .</p>
											</div>

										</div>
										<!-- /.col-lg-6 (nested) -->
									</fieldset>

								</div>
								<!-- /.row (nested) -->
							</div>
							<!-- /.panel-body -->
						</div>
						<!-- /.panel -->
					</div>
					<!-- /.col-lg-12 -->
				</div>
				<!-- /.row -->

				<div class="row">
					<div class="col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">Post information</div>
							<div>
								<div class="panel-body">
									<div class="row">
										<fieldset id="info2modify">
											<div class="col-lg-6">



												<div class="form-group">
													<label for="Select">Site</label> <select id="disabledSelect" class="form-control">
														<option>Disabled select1</option>
														<option>Disabled select2</option>
														<option>Disabled select3</option>
													</select>
												</div>

												<div class="form-group">
													<label for="select">agence</label> <select id="disabledSelect" class="form-control">
														<option>Disabled select1</option>
														<option>Disabled select2</option>
														<option>Disabled select3</option>
													</select>
												</div>

												<div class="form-group">
													<label>Manager</label> <input class="form-control" id="managerInput" type="text">
													<p class="help-block">You can either tape manager's Id or name, and then choose the manager existing in system.</p>
												</div>


											</div>
											<!-- /.col-lg-6 (nested) -->
											<div class="col-lg-6">


												<div class="form-group">
													<label for="select">Region</label> <select id="disabledSelect" class="form-control">
														<option>Disabled select1</option>
														<option>Disabled select2</option>
														<option>Disabled select3</option>
													</select>
												</div>

												<div class="form-group">
													<label for="select">Job</label> <select id="disabledSelect" class="form-control">
														<option>Trader</option>
														<option>Responsable</option>
														<option>Risk control officer</option>
													</select>
												</div>
												
												<div class="form-group">
													<label>Partner</label> <input class="form-control" id="managerInput" type="text">
													<p class="help-block">You can either tape partner's Id or name, and then choose the manager existing in system.</p>
												</div>

											</div>
											<!-- /.col-lg-6 (nested) -->
										</fieldset>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<div class="panel panel-default">
							<div class="panel-heading">Another basic Form Elements</div>
							<div>
								<p></p>
							</div>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-lg-12 text-center">

						<button type="submit" class="btn btn-primary btn-lg">Submit Button</button>

					</div>
				</div>
				<br>
			</form>
		</div>
		<!-- /#page-wrapper -->



	</div>
	<!-- /#wrapper -->

	<!-- jQuery -->
	<script src="scriptLibrary/jquery/dist/jquery.min.js"></script>

	<!-- Bootstrap Core JavaScript -->
	<script src="scriptLibrary/bootstrap/js/bootstrap.min.js"></script>


	
	</script>

</body>

</html>
